### PR TITLE
make demo more beautiful & fix CSS link

### PR DESCRIPTION
**Pull request by cydrobolt**
- fix CSS: the `<link>` tag is self-closing
- enclose page in bootstrap container
- add a simple intro
- fix some scaling issues
- create a demo CSS file to be used in the demo

+1s?

### CODE REVIEW

**Comment by cydrobolt** [comment]
Added one unrelated commit to this PR in order to avoid having to merge branches. Fixed many JS style issues
- missing semicolons
- not using `===` to compare with `null` or `undefined`
- not using dot notation when it could be used

**Comment by ralphbean** [comment]
Hi @Cydrobolt!  Two things:
- Can you post a screenshot of how it looks after the changes?
- I thought that `package` was a reserved word in js.  Does that `o.package` stuff really work?

**Comment by cydrobolt** [comment]
Yes, `o.package` works. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

`package` is a future reserved keyword only in strict mode. It cannot be used in variable names, but it should work perfectly fine as an array indice in dot notation. 

i.e `package.o` would not work, but `o.package` should work. 

Before:
img
After:
img

**Comment by ralphbean** [comment]
Looks great!  Thanks a ton!

**Pull request merged**
