### PR TITLE
Fix oddly shaped buttons on bootstrap sites.

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by pypingou** [comment]
Code wise :+1: for me

**Comment by ralphbean** [comment]
Screen shots of before and after:

fedmenu-before

fedmenu-after

**Comment by pypingou** [comment]
Looks good to me (I think this was the squashing I have seen on a couple of apps as well)

**Comment by ralphbean** [comment]
Thanks all!

**Pull request merged**
